version: '3'
services:
        redis:
                image: redis:latest
                ports:
                        - 6095:6379
                volumes:
                        - ./config/redis.conf:/redis.conf
                command: [ "redis-server", "/redis.conf"]
        web:
                build: ./web/ 
                container_name: flask_app
                ports:
                        - 5016:5000
                
        worker:
                build: ./worker/ 
                container_name: flask_worker
                volumes:
                       - ./worker/food.txt:/food.txt
                
                        

